version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: